package app.mybatis.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.math.BigDecimal;
import java.util.Date;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("prototype")
public class Auto_test {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.ID
     *
     * @mbg.generated
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.col1
     *
     * @mbg.generated
     */
    private String col1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.col2
     *
     * @mbg.generated
     */
    private Integer col2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c1
     *
     * @mbg.generated
     */
    private String c1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c2
     *
     * @mbg.generated
     */
    private Long c2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c5
     *
     * @mbg.generated
     */
    private String c5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c6
     *
     * @mbg.generated
     */
    private BigDecimal c6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c8
     *
     * @mbg.generated
     */
    private String c8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c10
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date c10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c11
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="hh:mm:ss",timezone="GMT+8")
    private Date c11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c12
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd hh:mm:ss",timezone="GMT+8")
    private Date c12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c13
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd hh:mm:ss",timezone="GMT+8")
    private Date c13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c14
     *
     * @mbg.generated
     */
    private Short c14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c15
     *
     * @mbg.generated
     */
    private Byte c15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c17
     *
     * @mbg.generated
     */
    private String c17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auto_test.c18
     *
     * @mbg.generated
     */
    private BigDecimal c18;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean ID_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean col1_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean col2_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c1_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c2_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c5_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c6_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c8_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c10_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c11_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c12_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c13_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c14_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c15_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c17_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    private boolean c18_changed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.ID
     *
     * @return the value of auto_test.ID
     *
     * @mbg.generated
     */
    @JsonProperty("ID")
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.ID
     *
     * @param ID the value for auto_test.ID
     *
     * @mbg.generated
     */
    @JsonProperty("ID")
    public void setID(Integer ID) {
        this.ID = ID;
        this.ID_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.col1
     *
     * @return the value of auto_test.col1
     *
     * @mbg.generated
     */
    @JsonProperty("col1")
    public String getCol1() {
        return col1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.col1
     *
     * @param col1 the value for auto_test.col1
     *
     * @mbg.generated
     */
    @JsonProperty("col1")
    public void setCol1(String col1) {
        this.col1 = col1 == null ? null : col1.trim();
        this.col1_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.col2
     *
     * @return the value of auto_test.col2
     *
     * @mbg.generated
     */
    @JsonProperty("col2")
    public Integer getCol2() {
        return col2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.col2
     *
     * @param col2 the value for auto_test.col2
     *
     * @mbg.generated
     */
    @JsonProperty("col2")
    public void setCol2(Integer col2) {
        this.col2 = col2;
        this.col2_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c1
     *
     * @return the value of auto_test.c1
     *
     * @mbg.generated
     */
    @JsonProperty("c1")
    public String getC1() {
        return c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c1
     *
     * @param c1 the value for auto_test.c1
     *
     * @mbg.generated
     */
    @JsonProperty("c1")
    public void setC1(String c1) {
        this.c1 = c1 == null ? null : c1.trim();
        this.c1_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c2
     *
     * @return the value of auto_test.c2
     *
     * @mbg.generated
     */
    @JsonProperty("c2")
    public Long getC2() {
        return c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c2
     *
     * @param c2 the value for auto_test.c2
     *
     * @mbg.generated
     */
    @JsonProperty("c2")
    public void setC2(Long c2) {
        this.c2 = c2;
        this.c2_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c5
     *
     * @return the value of auto_test.c5
     *
     * @mbg.generated
     */
    @JsonProperty("c5")
    public String getC5() {
        return c5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c5
     *
     * @param c5 the value for auto_test.c5
     *
     * @mbg.generated
     */
    @JsonProperty("c5")
    public void setC5(String c5) {
        this.c5 = c5 == null ? null : c5.trim();
        this.c5_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c6
     *
     * @return the value of auto_test.c6
     *
     * @mbg.generated
     */
    @JsonProperty("c6")
    public BigDecimal getC6() {
        return c6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c6
     *
     * @param c6 the value for auto_test.c6
     *
     * @mbg.generated
     */
    @JsonProperty("c6")
    public void setC6(BigDecimal c6) {
        this.c6 = c6;
        this.c6_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c8
     *
     * @return the value of auto_test.c8
     *
     * @mbg.generated
     */
    @JsonProperty("c8")
    public String getC8() {
        return c8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c8
     *
     * @param c8 the value for auto_test.c8
     *
     * @mbg.generated
     */
    @JsonProperty("c8")
    public void setC8(String c8) {
        this.c8 = c8 == null ? null : c8.trim();
        this.c8_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c10
     *
     * @return the value of auto_test.c10
     *
     * @mbg.generated
     */
    @JsonProperty("c10")
    public Date getC10() {
        return c10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c10
     *
     * @param c10 the value for auto_test.c10
     *
     * @mbg.generated
     */
    @JsonProperty("c10")
    public void setC10(Date c10) {
        this.c10 = c10;
        this.c10_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c11
     *
     * @return the value of auto_test.c11
     *
     * @mbg.generated
     */
    @JsonProperty("c11")
    public Date getC11() {
        return c11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c11
     *
     * @param c11 the value for auto_test.c11
     *
     * @mbg.generated
     */
    @JsonProperty("c11")
    public void setC11(Date c11) {
        this.c11 = c11;
        this.c11_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c12
     *
     * @return the value of auto_test.c12
     *
     * @mbg.generated
     */
    @JsonProperty("c12")
    public Date getC12() {
        return c12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c12
     *
     * @param c12 the value for auto_test.c12
     *
     * @mbg.generated
     */
    @JsonProperty("c12")
    public void setC12(Date c12) {
        this.c12 = c12;
        this.c12_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c13
     *
     * @return the value of auto_test.c13
     *
     * @mbg.generated
     */
    @JsonProperty("c13")
    public Date getC13() {
        return c13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c13
     *
     * @param c13 the value for auto_test.c13
     *
     * @mbg.generated
     */
    @JsonProperty("c13")
    public void setC13(Date c13) {
        this.c13 = c13;
        this.c13_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c14
     *
     * @return the value of auto_test.c14
     *
     * @mbg.generated
     */
    @JsonProperty("c14")
    public Short getC14() {
        return c14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c14
     *
     * @param c14 the value for auto_test.c14
     *
     * @mbg.generated
     */
    @JsonProperty("c14")
    public void setC14(Short c14) {
        this.c14 = c14;
        this.c14_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c15
     *
     * @return the value of auto_test.c15
     *
     * @mbg.generated
     */
    @JsonProperty("c15")
    public Byte getC15() {
        return c15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c15
     *
     * @param c15 the value for auto_test.c15
     *
     * @mbg.generated
     */
    @JsonProperty("c15")
    public void setC15(Byte c15) {
        this.c15 = c15;
        this.c15_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c17
     *
     * @return the value of auto_test.c17
     *
     * @mbg.generated
     */
    @JsonProperty("c17")
    public String getC17() {
        return c17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c17
     *
     * @param c17 the value for auto_test.c17
     *
     * @mbg.generated
     */
    @JsonProperty("c17")
    public void setC17(String c17) {
        this.c17 = c17 == null ? null : c17.trim();
        this.c17_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auto_test.c18
     *
     * @return the value of auto_test.c18
     *
     * @mbg.generated
     */
    @JsonProperty("c18")
    public BigDecimal getC18() {
        return c18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auto_test.c18
     *
     * @param c18 the value for auto_test.c18
     *
     * @mbg.generated
     */
    @JsonProperty("c18")
    public void setC18(BigDecimal c18) {
        this.c18 = c18;
        this.c18_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ID=").append(ID);
        sb.append(", col1=").append(col1);
        sb.append(", col2=").append(col2);
        sb.append(", c1=").append(c1);
        sb.append(", c2=").append(c2);
        sb.append(", c5=").append(c5);
        sb.append(", c6=").append(c6);
        sb.append(", c8=").append(c8);
        sb.append(", c10=").append(c10);
        sb.append(", c11=").append(c11);
        sb.append(", c12=").append(c12);
        sb.append(", c13=").append(c13);
        sb.append(", c14=").append(c14);
        sb.append(", c15=").append(c15);
        sb.append(", c17=").append(c17);
        sb.append(", c18=").append(c18);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c10_fmt_yyyy_MM_dd_HH_mm_ss")
    public String getC10_fmt_yyyy_MM_dd_HH_mm_ss() {
        if ( c10 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(c10);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c10_fmt_HH_mm_ss")
    public String getC10_fmt_HH_mm_ss() {
        if ( c10 == null) { return "";}
         return (new java.text.SimpleDateFormat("HH:mm:ss")).format(c10);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c10_fmt_yyyy_MM_dd")
    public String getC10_fmt_yyyy_MM_dd() {
        if ( c10 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd")).format(c10);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c11_fmt_yyyy_MM_dd_HH_mm_ss")
    public String getC11_fmt_yyyy_MM_dd_HH_mm_ss() {
        if ( c11 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(c11);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c11_fmt_HH_mm_ss")
    public String getC11_fmt_HH_mm_ss() {
        if ( c11 == null) { return "";}
         return (new java.text.SimpleDateFormat("HH:mm:ss")).format(c11);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c11_fmt_yyyy_MM_dd")
    public String getC11_fmt_yyyy_MM_dd() {
        if ( c11 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd")).format(c11);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c12_fmt_yyyy_MM_dd_HH_mm_ss")
    public String getC12_fmt_yyyy_MM_dd_HH_mm_ss() {
        if ( c12 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(c12);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c12_fmt_HH_mm_ss")
    public String getC12_fmt_HH_mm_ss() {
        if ( c12 == null) { return "";}
         return (new java.text.SimpleDateFormat("HH:mm:ss")).format(c12);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c12_fmt_yyyy_MM_dd")
    public String getC12_fmt_yyyy_MM_dd() {
        if ( c12 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd")).format(c12);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c13_fmt_yyyy_MM_dd_HH_mm_ss")
    public String getC13_fmt_yyyy_MM_dd_HH_mm_ss() {
        if ( c13 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(c13);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c13_fmt_HH_mm_ss")
    public String getC13_fmt_HH_mm_ss() {
        if ( c13 == null) { return "";}
         return (new java.text.SimpleDateFormat("HH:mm:ss")).format(c13);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    @JsonProperty("c13_fmt_yyyy_MM_dd")
    public String getC13_fmt_yyyy_MM_dd() {
        if ( c13 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd")).format(c13);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getID_changed() {
        return this.ID_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getCol1_changed() {
        return this.col1_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getCol2_changed() {
        return this.col2_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC1_changed() {
        return this.c1_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC2_changed() {
        return this.c2_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC5_changed() {
        return this.c5_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC6_changed() {
        return this.c6_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC8_changed() {
        return this.c8_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC10_changed() {
        return this.c10_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC11_changed() {
        return this.c11_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC12_changed() {
        return this.c12_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC13_changed() {
        return this.c13_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC14_changed() {
        return this.c14_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC15_changed() {
        return this.c15_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC17_changed() {
        return this.c17_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_test
     *
     * @mbg.generated
     */
    public boolean getC18_changed() {
        return this.c18_changed;
    }
}