package app.mybatis.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("prototype")
public class Sys_right_controller_method {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller_method.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller_method.controllerId
     *
     * @mbg.generated
     */
    private Integer controllerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller_method.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller_method.methodName
     *
     * @mbg.generated
     */
    private String methodName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller_method.matchUrl
     *
     * @mbg.generated
     */
    private String matchUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller_method.sysHas
     *
     * @mbg.generated
     */
    private Boolean sysHas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller_method.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller_method.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    private boolean id_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    private boolean controllerId_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    private boolean url_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    private boolean methodName_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    private boolean matchUrl_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    private boolean sysHas_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    private boolean memo_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    private boolean sort_changed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller_method.id
     *
     * @return the value of sys_right_controller_method.id
     *
     * @mbg.generated
     */
    @JsonProperty("id")
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller_method.id
     *
     * @param id the value for sys_right_controller_method.id
     *
     * @mbg.generated
     */
    @JsonProperty("id")
    public void setId(Integer id) {
        this.id = id;
        this.id_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller_method.controllerId
     *
     * @return the value of sys_right_controller_method.controllerId
     *
     * @mbg.generated
     */
    @JsonProperty("controllerId")
    public Integer getControllerId() {
        return controllerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller_method.controllerId
     *
     * @param controllerId the value for sys_right_controller_method.controllerId
     *
     * @mbg.generated
     */
    @JsonProperty("controllerId")
    public void setControllerId(Integer controllerId) {
        this.controllerId = controllerId;
        this.controllerId_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller_method.url
     *
     * @return the value of sys_right_controller_method.url
     *
     * @mbg.generated
     */
    @JsonProperty("url")
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller_method.url
     *
     * @param url the value for sys_right_controller_method.url
     *
     * @mbg.generated
     */
    @JsonProperty("url")
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
        this.url_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller_method.methodName
     *
     * @return the value of sys_right_controller_method.methodName
     *
     * @mbg.generated
     */
    @JsonProperty("methodName")
    public String getMethodName() {
        return methodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller_method.methodName
     *
     * @param methodName the value for sys_right_controller_method.methodName
     *
     * @mbg.generated
     */
    @JsonProperty("methodName")
    public void setMethodName(String methodName) {
        this.methodName = methodName == null ? null : methodName.trim();
        this.methodName_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller_method.matchUrl
     *
     * @return the value of sys_right_controller_method.matchUrl
     *
     * @mbg.generated
     */
    @JsonProperty("matchUrl")
    public String getMatchUrl() {
        return matchUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller_method.matchUrl
     *
     * @param matchUrl the value for sys_right_controller_method.matchUrl
     *
     * @mbg.generated
     */
    @JsonProperty("matchUrl")
    public void setMatchUrl(String matchUrl) {
        this.matchUrl = matchUrl == null ? null : matchUrl.trim();
        this.matchUrl_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller_method.sysHas
     *
     * @return the value of sys_right_controller_method.sysHas
     *
     * @mbg.generated
     */
    @JsonProperty("sysHas")
    public Boolean getSysHas() {
        return sysHas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller_method.sysHas
     *
     * @param sysHas the value for sys_right_controller_method.sysHas
     *
     * @mbg.generated
     */
    @JsonProperty("sysHas")
    public void setSysHas(Boolean sysHas) {
        this.sysHas = sysHas;
        this.sysHas_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller_method.memo
     *
     * @return the value of sys_right_controller_method.memo
     *
     * @mbg.generated
     */
    @JsonProperty("memo")
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller_method.memo
     *
     * @param memo the value for sys_right_controller_method.memo
     *
     * @mbg.generated
     */
    @JsonProperty("memo")
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
        this.memo_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller_method.sort
     *
     * @return the value of sys_right_controller_method.sort
     *
     * @mbg.generated
     */
    @JsonProperty("sort")
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller_method.sort
     *
     * @param sort the value for sys_right_controller_method.sort
     *
     * @mbg.generated
     */
    @JsonProperty("sort")
    public void setSort(Integer sort) {
        this.sort = sort;
        this.sort_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", controllerId=").append(controllerId);
        sb.append(", url=").append(url);
        sb.append(", methodName=").append(methodName);
        sb.append(", matchUrl=").append(matchUrl);
        sb.append(", sysHas=").append(sysHas);
        sb.append(", memo=").append(memo);
        sb.append(", sort=").append(sort);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    public boolean getId_changed() {
        return this.id_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    public boolean getControllerId_changed() {
        return this.controllerId_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    public boolean getUrl_changed() {
        return this.url_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    public boolean getMethodName_changed() {
        return this.methodName_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    public boolean getMatchUrl_changed() {
        return this.matchUrl_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    public boolean getSysHas_changed() {
        return this.sysHas_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    public boolean getMemo_changed() {
        return this.memo_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    public boolean getSort_changed() {
        return this.sort_changed;
    }
}