package app.mybatis.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("prototype")
public class Sys_right_group_detail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_group_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_group_detail.groupId
     *
     * @mbg.generated
     */
    private Integer groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_group_detail.methodId
     *
     * @mbg.generated
     */
    private Integer methodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    private boolean id_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    private boolean groupId_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    private boolean methodId_changed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_group_detail.id
     *
     * @return the value of sys_right_group_detail.id
     *
     * @mbg.generated
     */
    @JsonProperty("id")
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_group_detail.id
     *
     * @param id the value for sys_right_group_detail.id
     *
     * @mbg.generated
     */
    @JsonProperty("id")
    public void setId(Integer id) {
        this.id = id;
        this.id_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_group_detail.groupId
     *
     * @return the value of sys_right_group_detail.groupId
     *
     * @mbg.generated
     */
    @JsonProperty("groupId")
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_group_detail.groupId
     *
     * @param groupId the value for sys_right_group_detail.groupId
     *
     * @mbg.generated
     */
    @JsonProperty("groupId")
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
        this.groupId_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_group_detail.methodId
     *
     * @return the value of sys_right_group_detail.methodId
     *
     * @mbg.generated
     */
    @JsonProperty("methodId")
    public Integer getMethodId() {
        return methodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_group_detail.methodId
     *
     * @param methodId the value for sys_right_group_detail.methodId
     *
     * @mbg.generated
     */
    @JsonProperty("methodId")
    public void setMethodId(Integer methodId) {
        this.methodId = methodId;
        this.methodId_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", groupId=").append(groupId);
        sb.append(", methodId=").append(methodId);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    public boolean getId_changed() {
        return this.id_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    public boolean getGroupId_changed() {
        return this.groupId_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    public boolean getMethodId_changed() {
        return this.methodId_changed;
    }
}