package app.mybatis.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("prototype")
public class Sys_right_controller {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller.controllerClassName
     *
     * @mbg.generated
     */
    private String controllerClassName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller.matchUrl
     *
     * @mbg.generated
     */
    private String matchUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller.sysHas
     *
     * @mbg.generated
     */
    private Boolean sysHas;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller.memo
     *
     * @mbg.generated
     */
    private String memo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller.menuUrl
     *
     * @mbg.generated
     */
    private String menuUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller.domain
     *
     * @mbg.generated
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_right_controller.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    private boolean id_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    private boolean controllerClassName_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    private boolean matchUrl_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    private boolean sysHas_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    private boolean memo_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    private boolean sort_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    private boolean menuUrl_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    private boolean domain_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    private boolean model_changed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller.id
     *
     * @return the value of sys_right_controller.id
     *
     * @mbg.generated
     */
    @JsonProperty("id")
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller.id
     *
     * @param id the value for sys_right_controller.id
     *
     * @mbg.generated
     */
    @JsonProperty("id")
    public void setId(Integer id) {
        this.id = id;
        this.id_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller.controllerClassName
     *
     * @return the value of sys_right_controller.controllerClassName
     *
     * @mbg.generated
     */
    @JsonProperty("controllerClassName")
    public String getControllerClassName() {
        return controllerClassName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller.controllerClassName
     *
     * @param controllerClassName the value for sys_right_controller.controllerClassName
     *
     * @mbg.generated
     */
    @JsonProperty("controllerClassName")
    public void setControllerClassName(String controllerClassName) {
        this.controllerClassName = controllerClassName == null ? null : controllerClassName.trim();
        this.controllerClassName_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller.matchUrl
     *
     * @return the value of sys_right_controller.matchUrl
     *
     * @mbg.generated
     */
    @JsonProperty("matchUrl")
    public String getMatchUrl() {
        return matchUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller.matchUrl
     *
     * @param matchUrl the value for sys_right_controller.matchUrl
     *
     * @mbg.generated
     */
    @JsonProperty("matchUrl")
    public void setMatchUrl(String matchUrl) {
        this.matchUrl = matchUrl == null ? null : matchUrl.trim();
        this.matchUrl_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller.sysHas
     *
     * @return the value of sys_right_controller.sysHas
     *
     * @mbg.generated
     */
    @JsonProperty("sysHas")
    public Boolean getSysHas() {
        return sysHas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller.sysHas
     *
     * @param sysHas the value for sys_right_controller.sysHas
     *
     * @mbg.generated
     */
    @JsonProperty("sysHas")
    public void setSysHas(Boolean sysHas) {
        this.sysHas = sysHas;
        this.sysHas_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller.memo
     *
     * @return the value of sys_right_controller.memo
     *
     * @mbg.generated
     */
    @JsonProperty("memo")
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller.memo
     *
     * @param memo the value for sys_right_controller.memo
     *
     * @mbg.generated
     */
    @JsonProperty("memo")
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
        this.memo_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller.sort
     *
     * @return the value of sys_right_controller.sort
     *
     * @mbg.generated
     */
    @JsonProperty("sort")
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller.sort
     *
     * @param sort the value for sys_right_controller.sort
     *
     * @mbg.generated
     */
    @JsonProperty("sort")
    public void setSort(Integer sort) {
        this.sort = sort;
        this.sort_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller.menuUrl
     *
     * @return the value of sys_right_controller.menuUrl
     *
     * @mbg.generated
     */
    @JsonProperty("menuUrl")
    public String getMenuUrl() {
        return menuUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller.menuUrl
     *
     * @param menuUrl the value for sys_right_controller.menuUrl
     *
     * @mbg.generated
     */
    @JsonProperty("menuUrl")
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl == null ? null : menuUrl.trim();
        this.menuUrl_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller.domain
     *
     * @return the value of sys_right_controller.domain
     *
     * @mbg.generated
     */
    @JsonProperty("domain")
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller.domain
     *
     * @param domain the value for sys_right_controller.domain
     *
     * @mbg.generated
     */
    @JsonProperty("domain")
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
        this.domain_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_right_controller.model
     *
     * @return the value of sys_right_controller.model
     *
     * @mbg.generated
     */
    @JsonProperty("model")
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_right_controller.model
     *
     * @param model the value for sys_right_controller.model
     *
     * @mbg.generated
     */
    @JsonProperty("model")
    public void setModel(String model) {
        this.model = model == null ? null : model.trim();
        this.model_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", controllerClassName=").append(controllerClassName);
        sb.append(", matchUrl=").append(matchUrl);
        sb.append(", sysHas=").append(sysHas);
        sb.append(", memo=").append(memo);
        sb.append(", sort=").append(sort);
        sb.append(", menuUrl=").append(menuUrl);
        sb.append(", domain=").append(domain);
        sb.append(", model=").append(model);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    public boolean getId_changed() {
        return this.id_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    public boolean getControllerClassName_changed() {
        return this.controllerClassName_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    public boolean getMatchUrl_changed() {
        return this.matchUrl_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    public boolean getSysHas_changed() {
        return this.sysHas_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    public boolean getMemo_changed() {
        return this.memo_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    public boolean getSort_changed() {
        return this.sort_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    public boolean getMenuUrl_changed() {
        return this.menuUrl_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    public boolean getDomain_changed() {
        return this.domain_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller
     *
     * @mbg.generated
     */
    public boolean getModel_changed() {
        return this.model_changed;
    }
}