package app.mybatis.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("prototype")
public class Sys_ms_session_object {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ms_session_object.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ms_session_object.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ms_session_object.keyName
     *
     * @mbg.generated
     */
    private String keyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_ms_session_object.keyValue
     *
     * @mbg.generated
     */
    private String keyValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_ms_session_object
     *
     * @mbg.generated
     */
    private boolean id_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_ms_session_object
     *
     * @mbg.generated
     */
    private boolean token_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_ms_session_object
     *
     * @mbg.generated
     */
    private boolean keyName_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_ms_session_object
     *
     * @mbg.generated
     */
    private boolean keyValue_changed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ms_session_object.id
     *
     * @return the value of sys_ms_session_object.id
     *
     * @mbg.generated
     */
    @JsonProperty("id")
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ms_session_object.id
     *
     * @param id the value for sys_ms_session_object.id
     *
     * @mbg.generated
     */
    @JsonProperty("id")
    public void setId(Integer id) {
        this.id = id;
        this.id_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ms_session_object.token
     *
     * @return the value of sys_ms_session_object.token
     *
     * @mbg.generated
     */
    @JsonProperty("token")
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ms_session_object.token
     *
     * @param token the value for sys_ms_session_object.token
     *
     * @mbg.generated
     */
    @JsonProperty("token")
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
        this.token_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ms_session_object.keyName
     *
     * @return the value of sys_ms_session_object.keyName
     *
     * @mbg.generated
     */
    @JsonProperty("keyName")
    public String getKeyName() {
        return keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ms_session_object.keyName
     *
     * @param keyName the value for sys_ms_session_object.keyName
     *
     * @mbg.generated
     */
    @JsonProperty("keyName")
    public void setKeyName(String keyName) {
        this.keyName = keyName == null ? null : keyName.trim();
        this.keyName_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_ms_session_object.keyValue
     *
     * @return the value of sys_ms_session_object.keyValue
     *
     * @mbg.generated
     */
    @JsonProperty("keyValue")
    public String getKeyValue() {
        return keyValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_ms_session_object.keyValue
     *
     * @param keyValue the value for sys_ms_session_object.keyValue
     *
     * @mbg.generated
     */
    @JsonProperty("keyValue")
    public void setKeyValue(String keyValue) {
        this.keyValue = keyValue == null ? null : keyValue.trim();
        this.keyValue_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_session_object
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", token=").append(token);
        sb.append(", keyName=").append(keyName);
        sb.append(", keyValue=").append(keyValue);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_session_object
     *
     * @mbg.generated
     */
    public boolean getId_changed() {
        return this.id_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_session_object
     *
     * @mbg.generated
     */
    public boolean getToken_changed() {
        return this.token_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_session_object
     *
     * @mbg.generated
     */
    public boolean getKeyName_changed() {
        return this.keyName_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_session_object
     *
     * @mbg.generated
     */
    public boolean getKeyValue_changed() {
        return this.keyValue_changed;
    }
}