package app.mybatis.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Date;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("prototype")
public class Sys_my_session {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_my_session.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_my_session.userNickName
     *
     * @mbg.generated
     */
    private String userNickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_my_session.userId
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_my_session.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_my_session.userName
     *
     * @mbg.generated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_my_session.lastOperDatetime
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd hh:mm:ss",timezone="GMT+8")
    private Date lastOperDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    private boolean id_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    private boolean userNickName_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    private boolean userId_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    private boolean token_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    private boolean userName_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    private boolean lastOperDatetime_changed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_my_session.id
     *
     * @return the value of sys_my_session.id
     *
     * @mbg.generated
     */
    @JsonProperty("id")
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_my_session.id
     *
     * @param id the value for sys_my_session.id
     *
     * @mbg.generated
     */
    @JsonProperty("id")
    public void setId(Integer id) {
        this.id = id;
        this.id_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_my_session.userNickName
     *
     * @return the value of sys_my_session.userNickName
     *
     * @mbg.generated
     */
    @JsonProperty("userNickName")
    public String getUserNickName() {
        return userNickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_my_session.userNickName
     *
     * @param userNickName the value for sys_my_session.userNickName
     *
     * @mbg.generated
     */
    @JsonProperty("userNickName")
    public void setUserNickName(String userNickName) {
        this.userNickName = userNickName == null ? null : userNickName.trim();
        this.userNickName_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_my_session.userId
     *
     * @return the value of sys_my_session.userId
     *
     * @mbg.generated
     */
    @JsonProperty("userId")
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_my_session.userId
     *
     * @param userId the value for sys_my_session.userId
     *
     * @mbg.generated
     */
    @JsonProperty("userId")
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
        this.userId_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_my_session.token
     *
     * @return the value of sys_my_session.token
     *
     * @mbg.generated
     */
    @JsonProperty("token")
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_my_session.token
     *
     * @param token the value for sys_my_session.token
     *
     * @mbg.generated
     */
    @JsonProperty("token")
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
        this.token_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_my_session.userName
     *
     * @return the value of sys_my_session.userName
     *
     * @mbg.generated
     */
    @JsonProperty("userName")
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_my_session.userName
     *
     * @param userName the value for sys_my_session.userName
     *
     * @mbg.generated
     */
    @JsonProperty("userName")
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
        this.userName_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_my_session.lastOperDatetime
     *
     * @return the value of sys_my_session.lastOperDatetime
     *
     * @mbg.generated
     */
    @JsonProperty("lastOperDatetime")
    public Date getLastOperDatetime() {
        return lastOperDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_my_session.lastOperDatetime
     *
     * @param lastOperDatetime the value for sys_my_session.lastOperDatetime
     *
     * @mbg.generated
     */
    @JsonProperty("lastOperDatetime")
    public void setLastOperDatetime(Date lastOperDatetime) {
        this.lastOperDatetime = lastOperDatetime;
        this.lastOperDatetime_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userNickName=").append(userNickName);
        sb.append(", userId=").append(userId);
        sb.append(", token=").append(token);
        sb.append(", userName=").append(userName);
        sb.append(", lastOperDatetime=").append(lastOperDatetime);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    @JsonProperty("lastOperDatetime_fmt_yyyy_MM_dd_HH_mm_ss")
    public String getLastOperDatetime_fmt_yyyy_MM_dd_HH_mm_ss() {
        if ( lastOperDatetime == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(lastOperDatetime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    @JsonProperty("lastOperDatetime_fmt_HH_mm_ss")
    public String getLastOperDatetime_fmt_HH_mm_ss() {
        if ( lastOperDatetime == null) { return "";}
         return (new java.text.SimpleDateFormat("HH:mm:ss")).format(lastOperDatetime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    @JsonProperty("lastOperDatetime_fmt_yyyy_MM_dd")
    public String getLastOperDatetime_fmt_yyyy_MM_dd() {
        if ( lastOperDatetime == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd")).format(lastOperDatetime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    public boolean getId_changed() {
        return this.id_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    public boolean getUserNickName_changed() {
        return this.userNickName_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    public boolean getUserId_changed() {
        return this.userId_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    public boolean getToken_changed() {
        return this.token_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    public boolean getUserName_changed() {
        return this.userName_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    public boolean getLastOperDatetime_changed() {
        return this.lastOperDatetime_changed;
    }
}