package app.mybatis.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.math.BigDecimal;
import java.util.Date;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

@Component
@Scope("prototype")
public class T1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.ID
     *
     * @mbg.generated
     */
    private Integer ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.c1
     *
     * @mbg.generated
     */
    private String c1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.c2
     *
     * @mbg.generated
     */
    private Integer c2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.c3
     *
     * @mbg.generated
     */
    private BigDecimal c3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.c4
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd hh:mm:ss",timezone="GMT+8")
    private Date c4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.c6
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date c6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.c7
     *
     * @mbg.generated
     */
    @JsonFormat(pattern="hh:mm:ss",timezone="GMT+8")
    private Date c7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1.c5
     *
     * @mbg.generated
     */
    private String c5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t1
     *
     * @mbg.generated
     */
    private boolean ID_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t1
     *
     * @mbg.generated
     */
    private boolean c1_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t1
     *
     * @mbg.generated
     */
    private boolean c2_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t1
     *
     * @mbg.generated
     */
    private boolean c3_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t1
     *
     * @mbg.generated
     */
    private boolean c4_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t1
     *
     * @mbg.generated
     */
    private boolean c6_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t1
     *
     * @mbg.generated
     */
    private boolean c7_changed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t1
     *
     * @mbg.generated
     */
    private boolean c5_changed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1.ID
     *
     * @return the value of t1.ID
     *
     * @mbg.generated
     */
    @JsonProperty("ID")
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1.ID
     *
     * @param ID the value for t1.ID
     *
     * @mbg.generated
     */
    @JsonProperty("ID")
    public void setID(Integer ID) {
        this.ID = ID;
        this.ID_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1.c1
     *
     * @return the value of t1.c1
     *
     * @mbg.generated
     */
    @JsonProperty("c1")
    public String getC1() {
        return c1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1.c1
     *
     * @param c1 the value for t1.c1
     *
     * @mbg.generated
     */
    @JsonProperty("c1")
    public void setC1(String c1) {
        this.c1 = c1 == null ? null : c1.trim();
        this.c1_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1.c2
     *
     * @return the value of t1.c2
     *
     * @mbg.generated
     */
    @JsonProperty("c2")
    public Integer getC2() {
        return c2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1.c2
     *
     * @param c2 the value for t1.c2
     *
     * @mbg.generated
     */
    @JsonProperty("c2")
    public void setC2(Integer c2) {
        this.c2 = c2;
        this.c2_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1.c3
     *
     * @return the value of t1.c3
     *
     * @mbg.generated
     */
    @JsonProperty("c3")
    public BigDecimal getC3() {
        return c3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1.c3
     *
     * @param c3 the value for t1.c3
     *
     * @mbg.generated
     */
    @JsonProperty("c3")
    public void setC3(BigDecimal c3) {
        this.c3 = c3;
        this.c3_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1.c4
     *
     * @return the value of t1.c4
     *
     * @mbg.generated
     */
    @JsonProperty("c4")
    public Date getC4() {
        return c4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1.c4
     *
     * @param c4 the value for t1.c4
     *
     * @mbg.generated
     */
    @JsonProperty("c4")
    public void setC4(Date c4) {
        this.c4 = c4;
        this.c4_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1.c6
     *
     * @return the value of t1.c6
     *
     * @mbg.generated
     */
    @JsonProperty("c6")
    public Date getC6() {
        return c6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1.c6
     *
     * @param c6 the value for t1.c6
     *
     * @mbg.generated
     */
    @JsonProperty("c6")
    public void setC6(Date c6) {
        this.c6 = c6;
        this.c6_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1.c7
     *
     * @return the value of t1.c7
     *
     * @mbg.generated
     */
    @JsonProperty("c7")
    public Date getC7() {
        return c7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1.c7
     *
     * @param c7 the value for t1.c7
     *
     * @mbg.generated
     */
    @JsonProperty("c7")
    public void setC7(Date c7) {
        this.c7 = c7;
        this.c7_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1.c5
     *
     * @return the value of t1.c5
     *
     * @mbg.generated
     */
    @JsonProperty("c5")
    public String getC5() {
        return c5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1.c5
     *
     * @param c5 the value for t1.c5
     *
     * @mbg.generated
     */
    @JsonProperty("c5")
    public void setC5(String c5) {
        this.c5 = c5 == null ? null : c5.trim();
        this.c5_changed = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ID=").append(ID);
        sb.append(", c1=").append(c1);
        sb.append(", c2=").append(c2);
        sb.append(", c3=").append(c3);
        sb.append(", c4=").append(c4);
        sb.append(", c6=").append(c6);
        sb.append(", c7=").append(c7);
        sb.append(", c5=").append(c5);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    @JsonProperty("c4_fmt_yyyy_MM_dd_HH_mm_ss")
    public String getC4_fmt_yyyy_MM_dd_HH_mm_ss() {
        if ( c4 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(c4);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    @JsonProperty("c4_fmt_HH_mm_ss")
    public String getC4_fmt_HH_mm_ss() {
        if ( c4 == null) { return "";}
         return (new java.text.SimpleDateFormat("HH:mm:ss")).format(c4);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    @JsonProperty("c4_fmt_yyyy_MM_dd")
    public String getC4_fmt_yyyy_MM_dd() {
        if ( c4 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd")).format(c4);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    @JsonProperty("c6_fmt_yyyy_MM_dd_HH_mm_ss")
    public String getC6_fmt_yyyy_MM_dd_HH_mm_ss() {
        if ( c6 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(c6);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    @JsonProperty("c6_fmt_HH_mm_ss")
    public String getC6_fmt_HH_mm_ss() {
        if ( c6 == null) { return "";}
         return (new java.text.SimpleDateFormat("HH:mm:ss")).format(c6);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    @JsonProperty("c6_fmt_yyyy_MM_dd")
    public String getC6_fmt_yyyy_MM_dd() {
        if ( c6 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd")).format(c6);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    @JsonProperty("c7_fmt_yyyy_MM_dd_HH_mm_ss")
    public String getC7_fmt_yyyy_MM_dd_HH_mm_ss() {
        if ( c7 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")).format(c7);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    @JsonProperty("c7_fmt_HH_mm_ss")
    public String getC7_fmt_HH_mm_ss() {
        if ( c7 == null) { return "";}
         return (new java.text.SimpleDateFormat("HH:mm:ss")).format(c7);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    @JsonProperty("c7_fmt_yyyy_MM_dd")
    public String getC7_fmt_yyyy_MM_dd() {
        if ( c7 == null) { return "";}
         return (new java.text.SimpleDateFormat("yyyy-MM-dd")).format(c7);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    public boolean getID_changed() {
        return this.ID_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    public boolean getC1_changed() {
        return this.c1_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    public boolean getC2_changed() {
        return this.c2_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    public boolean getC3_changed() {
        return this.c3_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    public boolean getC4_changed() {
        return this.c4_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    public boolean getC6_changed() {
        return this.c6_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    public boolean getC7_changed() {
        return this.c7_changed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1
     *
     * @mbg.generated
     */
    public boolean getC5_changed() {
        return this.c5_changed;
    }
}