package app.mybatis.dao;

import app.mybatis.entity.Sys_my_session_object;
import app.mybatis.entity.Sys_my_session_objectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Sys_my_session_objectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    long countByExample(Sys_my_session_objectExample example);

    void createTable();
    int selectTableCount();
    void deleteByToken(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int deleteByExample(Sys_my_session_objectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int insert(Sys_my_session_object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int insertSelective(Sys_my_session_object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    List<Sys_my_session_object> selectByExampleWithBLOBs(Sys_my_session_objectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    List<Sys_my_session_object> selectByExample(Sys_my_session_objectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    Sys_my_session_object selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Sys_my_session_object record, @Param("example") Sys_my_session_objectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") Sys_my_session_object record, @Param("example") Sys_my_session_objectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Sys_my_session_object record, @Param("example") Sys_my_session_objectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sys_my_session_object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(Sys_my_session_object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sys_my_session_object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyChanged(Sys_my_session_object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int insertChanged(Sys_my_session_object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    int insertSqlserverChanged(Sys_my_session_object record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session_object
     *
     * @mbg.generated
     */
    List<Sys_my_session_object> selectSqlserverByExample(Sys_my_session_objectExample example);
}