package app.mybatis.dao;

import app.mybatis.entity.Sys_my_session;
import app.mybatis.entity.Sys_my_sessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Sys_my_sessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    long countByExample(Sys_my_sessionExample example);

    void createTable();
    int selectTableCount();
    void deleteByToken(String token);
    void clearTimeoutData(java.util.Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    int deleteByExample(Sys_my_sessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    int insert(Sys_my_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    int insertSelective(Sys_my_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    List<Sys_my_session> selectByExample(Sys_my_sessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    Sys_my_session selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Sys_my_session record, @Param("example") Sys_my_sessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Sys_my_session record, @Param("example") Sys_my_sessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sys_my_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sys_my_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyChanged(Sys_my_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    int insertChanged(Sys_my_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    int insertSqlserverChanged(Sys_my_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_my_session
     *
     * @mbg.generated
     */
    List<Sys_my_session> selectSqlserverByExample(Sys_my_sessionExample example);
}