package app.mybatis.dao;

import app.mybatis.entity.Sys_right_controller_method;
import app.mybatis.entity.Sys_right_controller_methodExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Sys_right_controller_methodMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    long countByExample(Sys_right_controller_methodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    int deleteByExample(Sys_right_controller_methodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    int insert(Sys_right_controller_method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    int insertSelective(Sys_right_controller_method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    List<Sys_right_controller_method> selectByExample(Sys_right_controller_methodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    Sys_right_controller_method selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Sys_right_controller_method record, @Param("example") Sys_right_controller_methodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Sys_right_controller_method record, @Param("example") Sys_right_controller_methodExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sys_right_controller_method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sys_right_controller_method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyChanged(Sys_right_controller_method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    int insertChanged(Sys_right_controller_method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    int insertSqlserverChanged(Sys_right_controller_method record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_controller_method
     *
     * @mbg.generated
     */
    List<Sys_right_controller_method> selectSqlserverByExample(Sys_right_controller_methodExample example);
}