package app.mybatis.dao;

import app.mybatis.entity.Sys_right_group_detail;
import app.mybatis.entity.Sys_right_group_detailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Sys_right_group_detailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    long countByExample(Sys_right_group_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    int deleteByExample(Sys_right_group_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    int insert(Sys_right_group_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    int insertSelective(Sys_right_group_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    List<Sys_right_group_detail> selectByExample(Sys_right_group_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    Sys_right_group_detail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Sys_right_group_detail record, @Param("example") Sys_right_group_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Sys_right_group_detail record, @Param("example") Sys_right_group_detailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sys_right_group_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sys_right_group_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyChanged(Sys_right_group_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    int insertChanged(Sys_right_group_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    int insertSqlserverChanged(Sys_right_group_detail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group_detail
     *
     * @mbg.generated
     */
    List<Sys_right_group_detail> selectSqlserverByExample(Sys_right_group_detailExample example);
}