package app.mybatis.dao;

import app.mybatis.entity.Sys_right_group;
import app.mybatis.entity.Sys_right_groupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Sys_right_groupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    long countByExample(Sys_right_groupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    int deleteByExample(Sys_right_groupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    int insert(Sys_right_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    int insertSelective(Sys_right_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    List<Sys_right_group> selectByExample(Sys_right_groupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    Sys_right_group selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Sys_right_group record, @Param("example") Sys_right_groupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Sys_right_group record, @Param("example") Sys_right_groupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sys_right_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sys_right_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyChanged(Sys_right_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    int insertChanged(Sys_right_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    int insertSqlserverChanged(Sys_right_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_right_group
     *
     * @mbg.generated
     */
    List<Sys_right_group> selectSqlserverByExample(Sys_right_groupExample example);
}