package app.mybatis.dao;

import app.mybatis.entity.Sys_ms_session;
import app.mybatis.entity.Sys_ms_sessionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Sys_ms_sessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    long countByExample(Sys_ms_sessionExample example);

    void createTable();
    int selectTableCount();
    void deleteByToken(String token);
    void clearTimeoutData(java.util.Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    int deleteByExample(Sys_ms_sessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    int insert(Sys_ms_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    int insertSelective(Sys_ms_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    List<Sys_ms_session> selectByExample(Sys_ms_sessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    Sys_ms_session selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Sys_ms_session record, @Param("example") Sys_ms_sessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Sys_ms_session record, @Param("example") Sys_ms_sessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Sys_ms_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sys_ms_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyChanged(Sys_ms_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    int insertChanged(Sys_ms_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    int insertSqlserverChanged(Sys_ms_session record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_ms_sessoin
     *
     * @mbg.generated
     */
    List<Sys_ms_session> selectSqlserverByExample(Sys_ms_sessionExample example);
}